
# render.yaml  (note the extension must be .yaml, not .yml)
services:
  - type: web
    name: bus-booking-system
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    internalPort: 8080      #  << add this line
    autoDeploy: true
